[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "llm-watermark"  
version = "0.1.0"       
description = "LLM text watermarking library for Capstone Design"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch",
    "transformers",
    "pandas",
    "tqdm",
    "spacy",
    "nltk",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"llm_watermark" = ["data/*", "homoglyph_data/*"]
